### ISSUE TITLE
Getting a script error warning after laptop wakes up from suspend.

### ISSUE THREAD

**Issue by cdysthe** [raelgc/scudcloud#250]
Lately I have been getting a script error warning after my laptop wakes up from suspend and the application window is unresponsive. I have to kill the process and restart. See screenshot below.

![scudcloud1](https://cloud.githubusercontent.com/assets/1281031/10314196/92595608-6c21-11e5-9b1d-b5fdfa43f551.png)

**Comment by raelgc** [comment]
Hi @cdysthe, thanks for reporting this issue.

Indeed, I started to get the same yesterday. I had to close and open ScudCloud again.

I'll investigate this and see if it's related to ScudCloud wake up activity or is just something internal to Slack reconnect JavaScript.

**Comment by raelgc** [comment]
Question: which distro are you using?

**Comment by raelgc** [comment]
I just published a fix for it. Please, upgrade and test if it's working.

**Comment by blueyed** [comment]
JFI: I have seen the same problem, and have just upgraded - which referenced this issue.  I have not tested yet if the fix is working.
Using Ubuntu FWIW.

**Comment by raelgc** [comment]
Thanks @blueyed

**Comment by rpbaptist** [comment]
I am using 1.0.76 and experience the same issue.

**Comment by blueyed** [comment]
@rpbaptist 
So it's not fixed for you?
Which distro are you using?

**Comment by raelgc** [comment]
@rpbaptist It's fixed in 1.0.76 from ScudCloud side. But can be the case where Slack reconnect JavaScript itself is using too much CPU from your machine.

**Comment by rpbaptist** [comment]
I am on Linux Mint 17.2 which is based on Ubuntu 14.04. Perhaps I overlooked something. Today I tried the official Slack app. I am not sure yet which one I will use. It seems solid.

Thanks for providing this excellent solution and picking up the ball dropped by Slack.

**Comment by raelgc** [comment]
Indeed guys, today I got this again. And it's not related to ScudCloud, but to Slack reconnect JavaScript. I'm thinking in a workaround. I'll test it in few minutes.

**Comment by cdysthe** [comment]
Sorry, been traveling. I am on Ubuntu 15.04. I will test the fix now.

**Comment by raelgc** [comment]
Ok, just published a new version to Ubuntu. Please, upgrade.

**Comment by cdysthe** [comment]
I'm still getting the scrupt error in 1.0-77 on Ubuntu 15.10 x64. It even happened when I did Help > About to find the version. Speaking of which, Help > About doesn't show up after the script error.

**Comment by raelgc** [comment]
Yeap, I got this today too again. While this time it took few seconds and get back to normal (except the `About` entry). Maybe its time to upgrade to Qt5, to see if it have a faster JS engine.

**Comment by raelgc** [comment]
I tested a simple fix now, which still displayed the not responding window for few seconds, but then got back. I clicked in `About` during the freeze, and several seconds later, it worked. I'll try this for this weekend, then on Monday I'll start the upgrade to Qt5 locally to see how it'll work.

**Comment by raelgc** [comment]
Today, after resume at the beginning of the day, I got the freeze again.

**Comment by iddqdidkfa** [comment]
I got a freeze too.

```
EDITION="MATE 64-bit"
DESCRIPTION="Linux Mint 17 Qiana"
```

**Comment by raelgc** [comment]
In the Qt5 port I'm testing, I got the freeze, but only for few seconds (it got back to work after the reconnect scripts got able to finish). The only problem with Qt5 version for now: the spell checker plugin is not marking bad words in red.

**Comment by iddqdidkfa** [comment]
I think main application functionality is more important then some plugin
(even so cool as spell checker). Maybe it's because I do not use it :)

вт, 13 окт. 2015 г. в 13:48, Rael Gugelmin Cunha notifications@github.com:

**Comment by raelgc** [comment]
Ok, published a new version. And today after resume I didn't face the freeze.

**Comment by iddqdidkfa** [comment]
Not upgraded to new version yet, but no freeze after resume this time.

**Comment by raelgc** [comment]
@iddqdidkfa I think Slack itself got back to use a less CPU intensive reconnect JavaScript. So, I just removed the workaround I've made.
