### ISSUE TITLE
Crashing in openSUSE

### ISSUE THREAD

**Issue by katnip1** [raelgc/scudcloud#588]
## ScudCloud Version

Paste the output for `scudcloud --version` below:
``1.60-2.1

## Distro and Desktop info

  - Distribution:openSUSE
  - Version/Release:Tumbleweed
  - Desktop environment:

## Expected behavior
to run

## Actual behavior

crashes on sign in to slack group

## Steps to reproduce
 1. open scudcloud
 2. sign into scudcloud slack group
 3. crashes

**Comment by raelgc** [comment]
Hi @katnip1. Thanks for raising this issue.

Please, post the complete output of `scudcloud --version`.

And, then, open scudcloud in the command line, and paste the output here too.

**Comment by katnip1** [comment]
scudcloud --version
ScudCloud 1.60
Python 3.6.1
Qt 5.9.0
PyQt 5.8.2
SIP 4.19.2

scudcloud opens fine via command line, no output

**Comment by raelgc** [comment]
Appears to be the same issue as #582: qt5-webkit was upgraded in Arch to a version that was crashing with Slack internal JS).

It was solved with Arch upgrade of qt5-webkit package to version 5.212.0alpha2-1.

**Comment by katnip1** [comment]
I tried to change things but with Tumbleweed being with more recent
versions of software, I get this still:

scudcloud --version
ScudCloud 1.60
Python 3.6.1
Qt 5.9.0
PyQt 5.8.2
SIP 4.19.2

suppose I wont get it to work then.
And it still crashes.

**Comment by katnip1** [comment]
scudcloud
Segmentation fault (core dumped)
