### ISSUE TITLE
Switch workspace opens workspace in default browser, not Scudcloud

### ISSUE THREAD

**Issue by LunkRat** [raelgc/scudcloud#608]
## ScudCloud Version

```ScudCloud 1.63
Python 3.5.2
Qt 5.5.1
WebKit 602.1
PyQt 5.5.1
SIP 4.17
```

## Distro and Desktop info

  - Distribution: ElementaryOS
  - Version/Release: Loki
  - Desktop environment: Gnome

## Expected behavior
Open alternate (signed-in) workspace in scudcloud

## Actual behavior
Alternate (signed-in) workspace opens in Chromium

## Steps to reproduce
 1. Sign in to more than one workspace
 2. Try to switch to another one
 3. Opens in Chromium

**Comment by raelgc** [comment]
@LunkRat Thanks for raising this. I've published a fix and packages for Ubuntu. 

Please, run a system upgrade and report feedback.

**Comment by LunkRat** [comment]
@raelgc indeed, it fixed the problem. I forgot that the UI has the teams/workspaces as icons on the leftmost black strip of the Sidebar. When I raised this issue, Scudcloud was not showing the team switcher icons at all. Now they appear and they work as expected. 

Thank you!

**Comment by raelgc** [comment]
@LunkRat Indeed, the leftbar was not appearing due the issue. Thank you for your time reporting and testing the issue!

**Comment by Vectornaut** [comment]
I remember installing a ScudCloud update around the time [the fix](https://github.com/raelgc/scudcloud/issues/608#issuecomment-358048452) was released, but I'm still having this issue. The new workspace opens in my default browser, Firefox.

### ScudCloud version
ScudCloud 1.64-1
Qt 5.5.1
WebKit _[can't figure out how to get version]_
PyQt 5.5.1
SIP 4.17

### Distribution and desktop information
Distribution: Ubuntu 16.04 LTS
Default web browser: Firefox 49.0
Desktop environment: Unity? _[whatever ships with Ubuntu 16.04...]_

**Comment by raelgc** [comment]
Slack has just change how their JS loads the teams list again (including several other minor changes)...

**Comment by MikkelOlsen** [comment]
I am also still having this problem..

ScudCloud version

ScudCloud 1.64-1
Qt 5.5.1
WebKit [can't figure out how to get version eiter]
PyQt 5.5.1
SIP 4.17
Distribution and desktop information

Distribution: Ubuntu 16.04 LTS
Default web browser: Firefox 49.0
Desktop environment: Unity

**Comment by raelgc** [comment]
I've published a new Ubuntu version, disabling the quicklist. But this time Slack changed a lot of their JS. I'm sure we'll face new issues.

**Comment by smaniscs** [comment]
This issue also occurs on Scudcloud version 1.65-2.fc28 on Fedora 28.    

P.S. Kudos to your whole team for the Linux love.

**Comment by smaniscs** [comment]
This issue also occurs on Scudcloud version 1.65-2.fc28 on Fedora 28.    Note that Scudcloud has to forward me over to onelogin.com for SSO authentication with the target Slack workspace,  which pops the default browser up for authentication.   It then opens the target Slack workspace in the browser just fine, so it's not a show stopper,  just a minor inconvenience.

P.S. Kudos to your whole team for the Linux love.
